// <auto-generated />
namespace FIT5032_MonashHotels_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dateOfBirthField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateOfBirthField));
        
        string IMigrationMetadata.Id
        {
            get { return "201909150703023_dateOfBirthField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
